version: 2
jobs:
  validate:
    filter:
      branch:
        only:
          - master
    docker:
      - image: hashicorp/packer:1.5.4
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate ubuntu-ami
          command: packer validate ./ubuntu-ami.json
  
  build:
    filter:
      branch:
        only:
          - master
    docker:
      - image: hashicorp/packer:1.5.4
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Create var.json
          command: echo { "aws_region" ":" "$AWS_REGION" "," "aws_access_key" ":" "$AWS_ACCESS_KEY" "," "aws_secret_key" ":" "$AWS_SECRET_KEY" "," "subnet_id" ":" "$SUBNET_ID" "," "source_ami" ":" "$SOURCE_AMI" "," "ami_users" ":" "$AMI_USERS" "," "ssh_username" ":" "$SSH_USERNAME" } >> var.json
      - run:
          name: Show var.json
          command: cat var.json
      - run:
          name: Show var.json
          command: ls -al
      - run:
          name: Build ubuntu-ami
          command: packer build -var-file="var.json" ubuntu-ami.json
          no_output_timeout: 30m
      - persist_to_workspace:
          root: .
          paths:
            - manifest-ubuntu-ami.json
      - store_artifacts:
          path: manifest-ubuntu-ami.json

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - build:
          requires:
            - validate

